name: DevSecOps Workflow

on:
  push:

jobs:
  component-scanning-job:
    name: Component Scanning Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Check the Node.js Version
        run: node --version

      - name: Install the Libraries or Node Modules
        run: npm install

  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Build Job Echo Statement
        run: echo "Build Job is Running"

      - name: Step 2 in Build Job Sleep
        run: sleep 10

  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Test Job Echo Statement
        run: echo "Test Job is Running"
      
      - name: Step 2 in Test Job Sleep
        run: sleep 10